### PR TITLE
implemented options when creating table (mysql and postgresql)

### PR DESCRIPTION
**Pull request by hubertlepicki**
This is implementation of 
https://github.com/elixir-lang/ecto/issues/678

Any good?

### CODE REVIEW

**Comment by josevalim** [comment]
Perfect.

**Comment by hubertlepicki** [comment]
Alright. So do I need to do anything more here, or this is just waiting to be merged, @josevalim ?

**Comment by josevalim** [comment]
Just waiting. I should do it first thing tomorrow. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by hubertlepicki** [comment]
Awesome

**Pull request merged**
