### PR TITLE
Add validate_required/2

### PR DESCRIPTION
**Pull request by paulcsmith**
This is being added as discussed in the mailing list:
https://groups.google.com/forum/#!topic/elixir-ecto/KDVPSglEdVw

### CODE REVIEW

**Comment by michalmuskala** [comment]
Maybe we should make the behaviour configurable? I saw @chrismccord proposed it:
```elixir
|> validate_required(fields, with: &(not is_nil(&1)))
```
The default behaviour would be the one implemented in the PR.

We can also make the message configurable.

**Comment by paulcsmith** [comment]
That's an interesting thought. I'm leaning toward not doing that though because I think you could just write your own function fairly easily at that point. It might be nice to get a validation message for free, but I don't know if it's that big of a win. It also seems like this might be something used in multiple models, so it might be better to extract your own function and use it elsewhere anyway. Maybe that's an incorrect assumption though?

**Comment by michalmuskala** [comment]
I was thinking about this a little bit more and I came to conclusion that what I want is a function similar to `validate_change` that would be always invoked, something like `validate_param` or `validate_field`. `validate_required` could be easily implemented in terms of such a function.

**Comment by paulcsmith** [comment]
I like the name validate_field and I like the idea as well. Would be cool if it could handle multiple fields name as well, but maybe that's out of scope. 

Any comments on this particular PR? Should I go ahead and add a validate_field function that validate_required uses under the hood?

**Comment by josevalim** [comment]
:-1: until we have at least one more function that needs it. :)

**Comment by paulcsmith** [comment]
Sounds good to me! :)

**Comment by paulcsmith** [comment]
Is there anything else this PR needs?

**Comment by josevalim** [comment]
I haven't checked it yet but if there is anything left I will let you know @paulcsmith! I am working on the adapter/associations part for now, I will focus on changesets later. Happy holidays!

**Comment by paulcsmith** [comment]
Sounds great! BTW I'll test the new associations stuff on ExMachina after the holidays. Happy holidays to you too!

**Comment by erikreedstrom** [comment]
@paulcsmith It seems the PR does not include an `:message` option as other validation functions do. I believe with the addition of gettext, this should be available.

**Pull request merged**
