### PR TITLE
Added ability to specify database options in repo config

### PR DESCRIPTION
**Pull request by janjiss**
Hey guys,
@DainisL found that there is no ability to add database options to repo. Here is a fix for that. Let us know if there are any adjustments needed.

Thanks

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you @janjiss! This whole thing is meant to be redesigned in the next Ecto release so I will hold on merging this for now.

**Comment by janjiss** [comment]
@josevalim Okay, tests are failing on the CI but not locally, perhaps its different Postgres version. Should we continue working on this or should we hold on till next version?

**Comment by josevalim** [comment]
Nice, let's hold until next version though. I actually think next version will also make it easier to support this.

**Comment by josevalim** [comment]
@janjiss, this feature has been added to master, thank you!

**Comment by janjiss** [comment]
@josevalim Thanks! Let me know if we need to change something

**Pull request closed without merging**
