### PR TITLE
Make order_by work in has_many through association

### PR DESCRIPTION
**Pull request by YoussefKababe**
Fix the order_by issue in has_many through associations.

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you @YoussefKababe. More important than the fix would be a test case. Can you write a test case inside the integration_test directory that reproduces your issue using the existing schemas? Thank you!

**Comment by YoussefKababe** [comment]
@josevalim I updated the tests and fixed what I did before!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by YoussefKababe** [comment]
:smile: :+1: :heart:

**Pull request merged**
