### PR TITLE
adapters/mysql: supports raw on non pk field

### PR DESCRIPTION
**Pull request by leiyangyou**
this is a quick and dirty fix that most likely should not get merged (and does not come with test)

### CODE REVIEW

**Comment by josevalim** [comment]
Excellent! Can you please provide a test case in the integration_test directory? You can run them as: `MIX_ENV=mysql mix test`. Thank you!

**Comment by josevalim** [comment]
Ping. :)

**Comment by josevalim** [comment]
Ping. :)

**Comment by leiyangyou** [comment]
Hi Valim,

Give me a couple days, i will get this updated :p

**Comment by leiyangyou** [comment]
Hi @josevalim 

not sure what your preferred organization for the adapter specific integration tests are, feel free to shuffle things around if needed.

also, I did not test the exceptional behaviour (where more than one raw field were requested), not sure if this fits for an integration test

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
