### PR TITLE
Include the type that failed to cast in changeset errors

### PR DESCRIPTION
**Pull request by wojtekmach**
See: https://github.com/elixir-lang/ecto/issues/1295

### CODE REVIEW

**Comment by josevalim** [comment]
Beautiful! Can you also do so for `cast_relation`? Please check if there are other places where we use "is invalid" as well.

**Comment by wojtekmach** [comment]
Thanks for mentioning relations, I thought about it for a while. What would be the most useful 'type' value in these cases? Just 'type: :assoc' or something more elaborate like: 'type: {:assoc, %Ecto.Association.Has{...}}'?

AFAIR the only remaining place is 'put_relation' but I'll double check and update accordingly.

**Comment by wojtekmach** [comment]
In a way, the only valid types for cast_relation and others are maps or lists of maps, so perhaps 'type: {:array, :map}'? I prefer something with assoc/embed though, idk :)

**Comment by josevalim** [comment]
Yes, `{:array, :map}` sounds good as well for the cast case.

**Comment by wojtekmach** [comment]
@ericmj or @michalmuskala do you have a preference about the best representation? Personally, I like `{:assoc, :one}` and `{:assoc, :many}` the most because it conveys the most information.

**Comment by michalmuskala** [comment]
If those are to be shown to the end user (like an API consumer) I think it makes sense to make `has_one` a `:map` and `has_many` an `{:array, :map}` - that's the form the client needs to send data in.

**Comment by wojtekmach** [comment]
> If those are to be shown to the end user (like an API consumer) I think it makes sense to make has_one a :map and has_many an {:array, :map} - that's the form the client needs to send data in.

Yeah, that makes sense too. My point of view was that these errors would go through `Changeset.traverse_errors` anyway, and so the developer would always have a chance to customize it (e.g. transform it to `{:array, :map}` if desired).

Anyway, I decided to move forward with `:map`, `{:array, :map}` and I just updated the PR. Let me know if anything is missing!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
