### PR TITLE
Datetime comparison

### PR DESCRIPTION
**Pull request by b0oh**
According to https://github.com/elixir-lang/ecto/issues/850

### CODE REVIEW

**Comment by b0oh** [comment]
Also I have received a proposal from @lexmag to rename Util to Utils.

**Comment by josevalim** [comment]
Looks great. We just need to add docs and it is ok to rename Util -> Utils.

**Comment by b0oh** [comment]
@josevalim, sorry, forgot to say yesterday that I updated pr.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
