### PR TITLE
Ecto :datetime and :time types handle native erlang datetime and time

### PR DESCRIPTION
**Pull request by gjaldon**
Closes https://github.com/elixir-lang/ecto/issues/648

### CODE REVIEW

**Comment by ericmj** [comment]
We need tests that verify that the values can be loaded/dumped. I don't think this change is enough to make it work.

**Comment by josevalim** [comment]
This change is enough but more tests do not hurt. :)

**Comment by gjaldon** [comment]
Added more tests to also cover dumping and loading in my latest push.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by gjaldon** [comment]
Thanks! :+1:

**Pull request merged**
