### PR TITLE
Allow multiple repos to be given to mix tasks.

### PR DESCRIPTION
**Pull request by bratsche**
Hi, this is my first attempt to contribute. This is an attempt to solve issue #935. Any comments will be much appreciated!

### CODE REVIEW

**Comment by bratsche** [comment]
One thing worth mentioning, `ecto.gen.repo` still doesn't generate multiple repos. It's getting kind of late and I need to get to sleep but I wanted to get this pushed tonight so I can get some comments, so what I did right now was make `ecto.gen.repo` issue a warning to the user and tell them that it can only generate one repo at a time.

**Comment by josevalim** [comment]
Thank you, a couple notes:

1. Please avoid pipeline if you are piping into a function. For example, `repos |> Enum.each(...)` should be `Enum.each repo, ...`

2. The syntax for parsing multiple repos must be:

    -r Foo -r Bar -r Baz

3. Finally, there is no need to support multiple repos with `ecto.gen.repo`, thank you!

**Comment by bratsche** [comment]
@josevalim Hi, thanks for your feedback! I've updated it to try to address your comments.

**Comment by bratsche** [comment]
Hi @josevalim I've rebased everything to a single commit now as you said on irc.

**Comment by bratsche** [comment]
Rebased again to fix merge conflicts

**Comment by bratsche** [comment]
Hi @josevalim, this one got out of sync again so I rebased again. Thanks!

**Comment by josevalim** [comment]
Sorry about this, I forgot about it. I will merge this today. :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by bratsche** [comment]
Awesome, thank you so much @josevalim!

**Pull request merged**
