### PR TITLE
Postgrex default opts in connection adapter

### PR DESCRIPTION
**Pull request by jquadrin**
Ensures postgrex default options are set.

addresses https://github.com/ericmj/postgrex/issues/160

### CODE REVIEW

**Comment by josevalim** [comment]
@ericmj is this public API? can we rely on it? /cc @fishcakez 

Thank you @jquadrin!

**Comment by fishcakez** [comment]
I'm not sure if it is public but I think we could make it so, @ericmj?

**Comment by ericmj** [comment]
Make it so.

On Friday, 12 February 2016, James Fish <notifications@github.com> wrote:

> I'm not sure if it is public but I think we could make it so, @ericmj
> <https://github.com/ericmj>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/pull/1246#issuecomment-183420035>.
>


-- 
Eric Meadows-Jönsson

**Comment by josevalim** [comment]
If we make it public, should we make it public in utils or part of the `Postgrex` API?

**Comment by jquadrin** [comment]
The latter may be more suitable. If so, something like this? https://github.com/jquadrin/postgrex/commit/6357389daf6b12fc221eaf8c4508fddf7b4d152c#diff-4a201588204577c700b0490f519fe322R334

**Comment by josevalim** [comment]
@jquadrin that patch looks good to me. ALthough we would need to document the function too. Thoughts @ericmj?

**Comment by fishcakez** [comment]
Perhaps it would be better to add `child_spec` to the Postgrex API and call that via `Ecto.Adapters.Postgres.Connection` - instead of `connection/2` and `DBConnection.child_spec/2`?

**Comment by josevalim** [comment]
@fishcakez sounds good to me too.

**Comment by jquadrin** [comment]
@fishcakez like this? https://github.com/jquadrin/ecto/commit/c96d54320d671f69ee30e656321caef990bc4b75 and this https://github.com/jquadrin/postgrex/commit/644564d93e0db4d3b712a59a57ad9624d658eff1 with `opts/1` defined in `Ecto.Adapters.Postgres.Connection`

**Comment by jquadrin** [comment]
Would need to make `opts/1` optional and also add it to the`Ecto.Adapters.SQL.Connection` behaviour

**Comment by josevalim** [comment]
I think he meant this. Instead of:

```elixir
{mod, opts} = connection.connection(opts)
DBConnection.child_spec(mod, opts)
```

We would write:

```elixir
connection.child_spec(opts)
```

And `child_spec` in the adapter would transform options as today and call `Postgrex.child_spec` that would normalize the options and return the childspec (by calling `DBConnection.child_spec`)

**Comment by josevalim** [comment]
Your implementation is postgrex is correct. :)

**Comment by jquadrin** [comment]
Closing and continuing here https://github.com/elixir-lang/ecto/pull/1247

**Pull request closed without merging**
