### PR TITLE
Add testcase for elixir-lang/ecto#1373

### PR DESCRIPTION
**Pull request by timbuchwaldt**
This adds a very basic testcase that hopefully models my problem from #1373

### CODE REVIEW

**Comment by josevalim** [comment]
Perfect, thank you! :)

**Comment by josevalim** [comment]
Btw @timbuchwaldt, if you can provide an integration test on the integration_test/cases/assoc.exs, it will be even better. :)

**Comment by timbuchwaldt** [comment]
Ah damn... the hand was quicker than the brain. Will do tomorrow :)

**Comment by josevalim** [comment]
@timbuchwaldt no worries, this is enough for me to get started. :)

**Comment by timbuchwaldt** [comment]
Ok, great :) I was wondering for about an hour if I'm holding sth wrong, but it seems like I'm not... puh!

**Pull request closed without merging**
