### PR TITLE
Documentation fix: #changeset

### PR DESCRIPTION
**Pull request by nicholaswyoung**
accepts map for params

### CODE REVIEW

**Comment by josevalim** [comment]
No spaces after `{` and before `}` please! And we have a similar example right after, can you please amend it too? Thank you!

**Comment by josevalim** [comment]
Btw, can you please verify your IRC client. For a couple nights you have been leaving and entering automatically, generate quite some noise. :)

**Comment by nicholaswyoung** [comment]
@josevalim I just updated the patch to match the style guidelines, and fixed the later example too.

As for the IRC client issues, I'm sorry for any mess. No idea what's causing that, unless it's my mobile client doing something weird. I've been offline for 8-9hrs at a time.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
