### PR TITLE
Adds support for Javascript date strings to Ecto.Date.cast/1

### PR DESCRIPTION
**Pull request by wless1**

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you! Just one tiny change: can you please reword the commit? We are not supporting "Javascript date", it is a known specification. Maybe something like: "Adds support for ISO datetime strings in Ecto.Date.cast/1"

**Comment by wless1** [comment]
Done!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by gjaldon** [comment]
:+1:

**Pull request merged**
