### PR TITLE
Fix LIKE and ILIKE clauses in MySQL adapter

### PR DESCRIPTION
**Pull request by tpunt**
MySQL does not have an `ILIKE` clause, and so attempting to use Ecto's `ilike` function results in an SQL error. MySQL's `LIKE` clause is case-insensitive by default, however, and so that can simply be used. Also, since Ecto's `like` function is suppose to be case-sensitive, we need to perform a binary string comparison in MySQL to get the desired behaviour.

### CODE REVIEW

**Comment by michalmuskala** [comment]
I'm not sure I agree with changing the database semantics of functions. I'd probably expect `like` to be translated straight into `LIKE` clause without any changes similar to how it's done today. The user should be aware of how database treats various functions. Furthermore `like` in the documentation gives no guarantees about case sensitivity. Because of this I'm against the change of `like` translating to `LIKE BINARY`.

Obviously broken `ilike` is an issue. A solution would be to raise an error explaining that MySQL does not support `ilike`, but I think we should rather support it in that case. Changing `ilike` to translate to the MySQL's `LIKE` is an acceptable solution.

**Comment by tpunt** [comment]
Hi Michał,

I can understand your view point for wanting a direct translation of Ecto's `like` to MySQL's `LIKE`, but I feel that it introduces unnecessary difficulties for developers. Without some form of basic abstraction, developers will be required to know how `LIKE` differentiates between different SQL dialects of different databases. If this inconsistency is not known, then moving from Postgres to another database may introduce subtle application bugs. If Ecto could provide some sort of consistent interface amongst databases, then this would simplify things for the developer.

So I feel like it would be better to have consistency amongst the `like` and `ilike` functions in Ecto, regardless of whichever database is used. Otherwise, developers will need to know the intricacies of inconsistencies between different DB SQL dialects and be forced to inject SQL code fragments for simple behaviours like this.

Good point on the documentation though. Seeing a case-insensitive version (`ilike`), I just assumed that `like` was for case-sensitive matchings (which it is for Postgres, even though it was not explicitly stated).

**Comment by michalmuskala** [comment]
I did a little research on how other databases behave:

* Postgres - `like` is case-sensitive, `ilike` is case-insensitive
* MySQL - `like` is case-insensitive
* SQL Server - `like` is case-insensitive
* SQLite - `like` is case-insensitive

Given that, it's rather postgres that is behaving "oddly" - `ilike` is a postgresql-only extension.

\cc @josevalim thoughts on that?

**Comment by josevalim** [comment]
I am not sure. In any occasion, `ILIKE` translating to `LIKE` or vice-versa would be confusing. I can see two options:

  1. Document LIKE and ILIKE behaviour are database specific

  2. Remove the two functions

**Comment by liveforeverx** [comment]
Reference to related discussion: https://github.com/xerions/mariaex/issues/78

**Comment by tpunt** [comment]
1. Document LIKE and ILIKE behaviour are database specific

Does this mean `ilike` should translate to `like` for all databases (other than Postgres)? Or that `ilike` should simply throw an error for all databases (other than Postgres)?

    2. Remove the two functions

For a common operation, it would be a shame to remove both functions from Ecto's library.

Given that `like` is predominantly case-insensitive, couldn't it be documented for case-insensitive matchings across all databases (incl. Postgres), and just remove `ilike` (since that didn't work for MySQL or SQLite anyway). For case-sensitive matchings, developers can instead use raw SQL according to their DB (Postgres = `LIKE`, MySQL = `LIKE BINARY`, SQLite = some weird hack, MSSQL = ...).

Whilst it's not ideal for Postgres to have `like` mapping to `ilike`, it would be consistent amongst all other databases. Plus case-insensitive matching seems to be the more common scenario anyway, so supporting it consistently across all databases from Ecto would be nice.

**Comment by josevalim** [comment]
So this means a third option. Supporting only `like` and make PG use ILIKE for it. 1, 2 or 3?

**Comment by VladShcherbin** [comment]
Maybe we can just write in the docs, that `ilike` is used only in PG, similar to how it is written in [PG docs](http://www.postgresql.org/docs/devel/static/functions-matching.html).

**Comment by ericmj** [comment]
I vote for creating a third (and fourth?) function that is consistent in case-handling in ecto. A new function means that users would not be confused if `like` in ecto does not work like it does in the underlying database and ecto would be consistent.

**Comment by michalmuskala** [comment]
I looked for how it's solved in other languages. Django offers `contains` that is case sensitive and `icontains` that is case insensitive. Maybe we could adopt those and deprecate `like` and `ilike`?

**Comment by josevalim** [comment]
The issue is that like supports special characters. If we call it "contains", we will support like's special characters still? Then will the documentation simply says: "uses the DB LIKE"?

**Comment by josevalim** [comment]
OK, we have decided to continue translating `like/2` directly to LIKE and remove `ilike/2` from MySQL. The reasoning is: there is no way `like` can behave consistently across databases, specially because each database support a different combination of characters and escape sequences: http://stackoverflow.com/questions/712580/list-of-special-characters-for-sql-like-clause.

In particular, MySQL is not always case sensitive or insensitive, it depends on the character collation.

I also think it suits well with Ecto's philosophy of staying closer to the database instead of trying to mimic features. Thanks everyone for the input and feedback.

**Comment by kenken1mura** [comment]
delet

**Comment by kenken1mura** [comment]
delet

**Comment by kenken1mura** [comment]
delet

**Comment by kenken1mura** [comment]
d

**Pull request closed without merging**
