### PR TITLE
added cast/to_string

### LINKED ISSUE #385: Provide an explicit Ecto.DateTime type with casting

### PR DESCRIPTION
**Pull request by briksoftware**
Closes #385

### CODE REVIEW

**Comment by briksoftware** [comment]
I have added very very simple (but supposedly fast) parsing for now

**Comment by briksoftware** [comment]
should I add the +00:00 format and missing timezone to be more flexible?

**Comment by josevalim** [comment]
This looks *great*. I wouldn't add `+00:00` nor timezones but I would also parse `yyyy-mm-dd hh:mm:ss` in the datetime.

Also, should we add a simple validation (just check they are in the proper boundary) or no?

**Comment by briksoftware** [comment]
I am still unsure about `+00:00` since it has the same meaning as `Z` so it would fit in ISO8061 UTC definition. Also adding it costs basically nothing. I am adding the timezone-less format `yyyy-mm-dd hh:mm:ss` as well as `hh:mm:ssZ` for time.

Adding validation like month <= 12, day <= 31, etc would be trivial and can be done in guards. I would not validate the month/day combination however. What do you think?

**Comment by josevalim** [comment]
Let's leave timezone out until someone asks. :) Agreed with everything else
though.

I also just realized that the datetime cast could just call the date and
time ones once we split them. Not sure if it helps implementation wise. :)


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by briksoftware** [comment]
basic validation is added and time without a timezone can also be read

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
