### PR TITLE
Fix links to the docs in the README

### PR DESCRIPTION
**Pull request by solnic**
[ci skip]

### CODE REVIEW

**Comment by ericmj** [comment]
The current links are actually better because if Ecto.html no longer is at the root of the docs we need to update the links.

**Comment by solnic** [comment]
currently those links give 404 so I'm not entirely sure how that's better :)

**Comment by ericmj** [comment]
Works on my machine, I get a 302.

**Comment by solnic** [comment]
I'm being redirected to `http://hexdocs.pm/Ecto.html` and it returns 404 ¯\_(⊙_ʖ⊙)_/¯

**Comment by ericmj** [comment]
What browser or HTTP client are you using?

On Fri, Oct 9, 2015 at 5:09 PM, Piotr Solnica <notifications@github.com>
wrote:

> I'm being redirected to http://hexdocs.pm/Ecto.html and it returns 404
> ¯_(⊙*ʖ⊙)*/¯
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/pull/1008#issuecomment-146997414>.
>



-- 
Eric Meadows-Jönsson

**Comment by ericmj** [comment]
Does both `http://hexdocs.pm/ecto` and `http://hexdocs.pm/ecto/` redirect to `http://hexdocs.pm/Ecto.html`?

**Comment by solnic** [comment]
hah, the latter works! so `http://hexdocs.pm/ecto/` works for me

**Comment by ericmj** [comment]
That's very strange, I don't see how `http://hexdocs.pm/ecto` can redirect to `http://hexdocs.pm/Ecto.html`.

It's supposed to be `http://hexdocs.pm/ecto` (302) => `http://hexdocs.pm/ecto/` (javascript redirect) => `http://hexdocs.pm/ecto/Ecto.html`.

**Comment by ericmj** [comment]
@solnic Do you still have the redirect issues?

**Comment by solnic** [comment]
@ericmj this weird but now it works for me, the only thing that changed is...my location

**Pull request closed without merging**
